describe('Forbidden Seal', function()
    ---@type CClientEntityPair
    local player

    before_each(function()
        player = xi.test.world:spawnPlayer({ zone = xi.zone.GM_HOME, job = xi.job.BLU, level = 20 })
        player:changesJob(xi.job.WHM)
        player:setsLevel(10)
        player:addSpell(xi.magic.spell.PROTECT)
        player:setMod(xi.mod.CONSERVE_MP, 0)
        player:setMod(xi.mod.NO_SPELL_MP_DEPLETION, 0)
        player:setMod(xi.mod.MP_COST_REDUCTION, 0)
        player:setHP(player:getMaxHP())
        player:setMP(0)
    end)

    local function activate()
        player.actions:useAbility(player, xi.jobAbility.FORBIDDEN_SEAL)
        xi.test.world:tickEntity(player)
        xi.test.world:skipTime(3)
        player.assert:hasEffect(xi.effect.FORBIDDEN_SEAL)
    end

    local function cast(spellId)
        player.actions:useSpell(player, spellId)
        xi.test.world:tickEntity(player)
        xi.test.world:skipTime(5)
        xi.test.world:skipTime(3)
    end

    it('unlocks at BLU 10, with the original icon but not the original status', function()
        player:setLevel(9)
        player.actions:useAbility(player, xi.jobAbility.FORBIDDEN_SEAL)
        xi.test.world:tickEntity(player)
        player.assert.no:hasEffect(xi.effect.FORBIDDEN_SEAL)

        player:setLevel(10)
        activate()
        player.assert.no:hasEffect(xi.effect.UNBRIDLED_WISDOM)
        assert(player:getStatusEffect(xi.effect.FORBIDDEN_SEAL):getIcon() == xi.effect.UNBRIDLED_WISDOM)
        assert(player:getMod(xi.mod.CONSERVE_MP) == 0)
        assert(player:hasRecast(xi.recast.ABILITY, 82))
        assert(not player:hasRecast(xi.recast.ABILITY, xi.recastID.SPECIAL2))
    end)

    it('has a ten-minute recast and a sixty-second buff window', function()
        activate()
        xi.test.world:skipTime(61)
        player.assert.no:hasEffect(xi.effect.FORBIDDEN_SEAL)
        assert(player:hasRecast(xi.recast.ABILITY, 82))
        xi.test.world:skipTime(525)
        assert(player:hasRecast(xi.recast.ABILITY, 82))
        xi.test.world:skipTime(15)
        assert(not player:hasRecast(xi.recast.ABILITY, 82))
    end)

    it('pays a White Magic spell with HP at zero MP', function()
        activate()
        local hp = player:getHP()
        cast(xi.magic.spell.PROTECT)
        player.assert:hasEffect(xi.effect.PROTECT)
        player.assert.no:hasEffect(xi.effect.FORBIDDEN_SEAL)
        assert(player:getHP() == hp - 9)
        assert(player:getMP() == 0)
    end)

    it('pays a Black Magic spell with HP at zero MP', function()
        player:changesJob(xi.job.BLM)
        player:setsLevel(10)
        player:addSpell(xi.magic.spell.BLAZE_SPIKES)
        player:setMod(xi.mod.CONSERVE_MP, 0)
        player:setMP(0)
        activate()
        local hp = player:getHP()
        cast(xi.magic.spell.BLAZE_SPIKES)
        player.assert:hasEffect(xi.effect.BLAZE_SPIKES)
        player.assert.no:hasEffect(xi.effect.FORBIDDEN_SEAL)
        assert(player:getHP() == hp - 8)
        assert(player:getMP() == 0)
    end)

    it('pays a set Blue Magic spell with HP at zero MP', function()
        player:addSpell(xi.magic.spell.COCOON)
        player.actions:setBlueSpells({ xi.magic.spell.COCOON })
        xi.test.world:skipTime(61)
        activate()
        local hp = player:getHP()
        cast(xi.magic.spell.COCOON)
        player.assert:hasEffect(xi.effect.DEFENSE_BOOST)
        player.assert.no:hasEffect(xi.effect.FORBIDDEN_SEAL)
        assert(player:getHP() == hp - 10)
        assert(player:getMP() == 0)
    end)

    it('uses the modified MP cost', function()
        player:setMod(xi.mod.MP_COST_REDUCTION, 50)
        activate()
        local hp = player:getHP()
        cast(xi.magic.spell.PROTECT)
        assert(player:getHP() == hp - 4)
        assert(player:getMP() == 0)
        player.assert.no:hasEffect(xi.effect.FORBIDDEN_SEAL)
    end)

    it('applies Conserve MP before converting the payment to HP', function()
        player:setMod(xi.mod.CONSERVE_MP, 100)
        activate()
        local hp = player:getHP()
        cast(xi.magic.spell.PROTECT)
        local paid = hp - player:getHP()
        assert(paid >= 4 and paid <= 8)
        assert(player:getMP() == 0)
        player.assert.no:hasEffect(xi.effect.FORBIDDEN_SEAL)
    end)

    it('caps an HP payment below the maximum HP at the current HP minus one', function()
        activate()
        player:setHP(5)
        cast(xi.magic.spell.PROTECT)
        player.assert:hasEffect(xi.effect.PROTECT)
        player.assert.no:hasEffect(xi.effect.FORBIDDEN_SEAL)
        assert(player:getHP() == 1)
        assert(player:getMP() == 0)
    end)

    it('caps a spell costing more than maximum HP at one remaining HP', function()
        activate()
        player:addListener('MAGIC_START', 'TEST_FORBIDDEN_SEAL_COST', function(caster, target, spell)
            spell:setMPCost(caster:getMaxHP() + 500)
        end)

        cast(xi.magic.spell.PROTECT)
        player:removeListener('TEST_FORBIDDEN_SEAL_COST')
        player.assert:hasEffect(xi.effect.PROTECT)
        player.assert.no:hasEffect(xi.effect.FORBIDDEN_SEAL)
        assert(player:getHP() == 1)
        assert(player:getMP() == 0)
    end)

    it('works at one HP and still consumes the seal', function()
        activate()
        player:setHP(1)
        cast(xi.magic.spell.PROTECT)
        player.assert:hasEffect(xi.effect.PROTECT)
        player.assert.no:hasEffect(xi.effect.FORBIDDEN_SEAL)
        assert(player:getHP() == 1)
        assert(player:getMP() == 0)
    end)

    it('charges once for an AoE spell', function()
        local ally = xi.test.world:spawnPlayer({ zone = xi.zone.GM_HOME, job = xi.job.WHM, level = 20 })
        player.actions:inviteToParty(ally)
        ally.actions:acceptPartyInvite()
        local pos = player:getPos()
        ally:setPos(pos.x, pos.y, pos.z)
        player:addSpell(xi.magic.spell.PROTECTRA)
        activate()
        local hp = player:getHP()
        cast(xi.magic.spell.PROTECTRA)
        player.assert:hasEffect(xi.effect.PROTECT)
        ally.assert:hasEffect(xi.effect.PROTECT)
        assert(player:getHP() == hp - 9)
        assert(player:getMP() == 0)
        player.assert.no:hasEffect(xi.effect.FORBIDDEN_SEAL)
    end)

    it('does not charge or consume the seal for an interrupted cast', function()
        activate()
        local hp = player:getHP()
        player.actions:useSpell(player, xi.magic.spell.PROTECT)
        xi.test.world:tickEntity(player)
        player:addStatusEffect(xi.effect.SILENCE, { duration = 30, origin = player })
        xi.test.world:skipTime(5)
        player.assert.no:hasEffect(xi.effect.PROTECT)
        player.assert:hasEffect(xi.effect.FORBIDDEN_SEAL)
        assert(player:getHP() == hp)
        assert(player:getMP() == 0)
    end)

    it('does not charge or consume the seal when Manafont makes the spell free', function()
        activate()
        player:addStatusEffect(xi.effect.MANAFONT, { duration = 30, origin = player })
        local hp = player:getHP()
        cast(xi.magic.spell.PROTECT)
        player.assert:hasEffect(xi.effect.PROTECT)
        player.assert:hasEffect(xi.effect.FORBIDDEN_SEAL)
        assert(player:getHP() == hp)
        assert(player:getMP() == 0)
    end)

    it('cannot finish a free cast if the seal is removed mid-cast', function()
        activate()
        local hp = player:getHP()
        player.actions:useSpell(player, xi.magic.spell.PROTECT)
        xi.test.world:tickEntity(player)
        player:delStatusEffect(xi.effect.FORBIDDEN_SEAL)
        xi.test.world:skipTime(5)
        player.assert.no:hasEffect(xi.effect.PROTECT)
        assert(player:getHP() == hp)
        assert(player:getMP() == 0)
    end)

    it('does not consume the seal for a zero final MP cost', function()
        player:setMod(xi.mod.NO_SPELL_MP_DEPLETION, 100)
        activate()
        local hp = player:getHP()
        cast(xi.magic.spell.PROTECT)
        player.assert:hasEffect(xi.effect.PROTECT)
        player.assert:hasEffect(xi.effect.FORBIDDEN_SEAL)
        assert(player:getHP() == hp)
        assert(player:getMP() == 0)
    end)

    it('returns to normal MP payment on the next spell', function()
        player:setMP(player:getMaxMP())
        activate()
        local mp = player:getMP()
        cast(xi.magic.spell.PROTECT)
        assert(player:getMP() == mp)
        local hp = player:getHP()
        cast(xi.magic.spell.PROTECT)
        assert(player:getHP() == hp)
        assert(player:getMP() == mp - 9)
    end)
end)
