describe('Sanctum Stoneskin casting', function()
    ---@type CClientEntityPair
    local player

    before_each(function()
        player = xi.test.world:spawnPlayer({ zone = xi.zone.GM_HOME, job = xi.job.SCH, level = 75 })
        player:changesJob(xi.job.RDM)
        player:setsLevel(37)
        player:addSpell(xi.magic.spell.STONESKIN)
    end)

    local function cast()
        player:setMP(player:getMaxMP())
        player.actions:useSpell(player, xi.magic.spell.STONESKIN)
        xi.test.world:tickEntity(player)
        xi.test.world:skipTime(10)
        player.assert:hasEffect(xi.effect.STONESKIN)
        return player:getStatusEffect(xi.effect.STONESKIN)
    end

    it('refreshes equal potency and expiration through normal casting', function()
        local power = cast():getPower()
        xi.test.world:skipTime(31)
        local remaining = player:getStatusEffect(xi.effect.STONESKIN):getTimeRemaining()
        local effect = cast()
        assert(effect:getPower() == power)
        assert(effect:getTimeRemaining() > remaining)
        assert(player:getMod(xi.mod.STONESKIN) == power)
    end)

    it('restores a depleted absorption pool', function()
        local power = cast():getPower()
        assert(power > 1)
        player:setMod(xi.mod.STONESKIN, 1)
        xi.test.world:skipTime(31)
        cast()
        assert(player:getMod(xi.mod.STONESKIN) == power)
    end)

    it('refreshes each Accession recipient', function()
        local ally = xi.test.world:spawnPlayer({ zone = xi.zone.GM_HOME, job = xi.job.WHM, level = 75 })
        player.actions:inviteToParty(ally)
        ally.actions:acceptPartyInvite()
        local pos = player:getPos()
        ally:setPos(pos.x, pos.y, pos.z)
        player:addStatusEffect(xi.effect.ACCESSION, { power = 1, duration = 60, origin = player })
        cast()
        ally.assert:hasEffect(xi.effect.STONESKIN)
        local power = ally:getMod(xi.mod.STONESKIN)
        ally:setMod(xi.mod.STONESKIN, 1)
        xi.test.world:skipTime(61)
        local remaining = ally:getStatusEffect(xi.effect.STONESKIN):getTimeRemaining()
        player:addStatusEffect(xi.effect.ACCESSION, { power = 1, duration = 60, origin = player })
        cast()
        assert(ally:getMod(xi.mod.STONESKIN) == power)
        assert(ally:getStatusEffect(xi.effect.STONESKIN):getTimeRemaining() > remaining)
    end)

    it('keeps the old shield when the recast is interrupted', function()
        local power = cast():getPower()
        xi.test.world:skipTime(31)
        local remaining = player:getStatusEffect(xi.effect.STONESKIN):getTimeRemaining()
        player.actions:useSpell(player, xi.magic.spell.STONESKIN)
        xi.test.world:tickEntity(player)
        player:addStatusEffect(xi.effect.SILENCE, { duration = 30, origin = player })
        xi.test.world:skipTime(10)
        player.assert:hasEffect(xi.effect.STONESKIN)
        assert(player:getMod(xi.mod.STONESKIN) == power)
        assert(player:getStatusEffect(xi.effect.STONESKIN):getTimeRemaining() < remaining)
    end)

    it('leaves an existing Earthen Ward shield untouched', function()
        player:addStatusEffect(xi.effect.STONESKIN, { power = 1, duration = 900, origin = player, tier = 3 })
        local remaining = player:getStatusEffect(xi.effect.STONESKIN):getTimeRemaining()
        local effect = cast()
        assert(effect:getTier() == 3)
        assert(effect:getPower() == 1)
        assert(effect:getTimeRemaining() < remaining)
        assert(player:getMod(xi.mod.STONESKIN) == 1)
    end)
end)
